config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'users#show'
  #post 'check', to: 'users#view'

  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  get 'users/new'

  get 'signin', to: 'sessions#new'
  post 'signin', to: 'sessions#create'
  delete 'signout', to: 'sessions#destroy'


  #taskに関してのルーティング
  resources :tasks

  get 'search' => 'tasks#search'
  #post '/' ,to: 'tasks#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
    validates :content, presence: true, length: {maximum:255}

    validates :status, presence: true, inclusion: { in: ["todo", "done"] }
    STATUSES = [:todo, :done]

    belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email.downcase! }

    validates :name, presence: true, length: { maximum: 20 }
    validates :email, presence: true, length: { maximum: 255 },
                format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                uniqueness: { case_sensitive: false }
    has_secure_password

    has_many :tasks
    has_many :favorites

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
    def require_logged_in
        unless logged_in?
            flash[:danger] = 'ログインしてください'
            redirect_to signin_url
        end
    end

    def already_logged_in
        if logged_in?
            flash[:danger] = 'すでにログインしています'
            redirect_to root_path
        end

    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :require_logged_in, only: [:destroy]
  before_action :already_logged_in, only: [:new, :create]

  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email,password)
        flash[:success] = 'ログインしました'
        redirect_to root_path
    else
      flash.now[:danger] = 'ログインできませんでした'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました'
    redirect_to signin_url
  end

  private
    def login(email, password)
      @user = User.find_by(email: email)
      if @user && @user.authenticate(password)
        session[:user_id] = @user.id
        return true
      else
        return false
      end
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :require_logged_in
  before_action :set_task, only: [:update, :destroy,:show]
  before_action :correct_user, only: [:update, :destroy]

  def create
    @task = current_user.tasks.build(task_params)
    if @task.save
      flash[:success] = "追加しました"
      redirect_back(fallback_location: root_path) 
    else
      flash[:danger] = "追加できませんでした"
      redirect_back(fallback_location: root_path) 
    end
  end
  
  def update
    if @task.update(task_params)
      flash[:success] = "『#{@task.content}』を更新しました"
      redirect_back(fallback_location: root_path) 
  
    else
      flash.now[:danger] = "更新できませんでした"
      redirect_back(fallback_location: root_path) 
    end
  end

  def destroy
    content = @task.content
    @task.destroy
    flash[:success] = "『#{content}』を削除しました"
    redirect_back(fallback_location: root_path) 
  end

  def search
    #deadlineの3つ分かれているパラメータの受け取り
    deadline_year = params["deadline(1i)"]
    deadline_month = params["deadline(2i)"]
    deadline_day = params["deadline(3i)"]
    # deadlineを指定していればdeadlineオブジェクトを生成
    if deadline_year.present? & deadline_month.present? & deadline_day.present? 
      deadline = "#{deadline_year}-#{deadline_month}-#{deadline_day}"
    # そうでなければnil
    else
      deadline = nil
    end
    redirect_to root_path(keyword: params[:keyword] ,deadline: deadline)
  end  

  private
  def task_params
    params.require(:task).permit(:content,:deadline,:status,:estimated_time)
  end

  def set_task
    @task = Task.find(params[:id])
  end

  def correct_user
    unless @task.user_id == current_user.id
      redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_logged_in, only: [:show]
  before_action :already_logged_in, only: [:new, :create]

  def show
    @user = User.find_by(id: session[:user_id])
    if !@user
      return redirect_to signin_path
    end
    #以下で全件を取得している。
    #current_user.tasks.allで全件、page~.でページネーションに関する記述
    #perで表示形式の変更
    deadline = params[:deadline]
    keyword = params[:keyword]

    if deadline.present?#ここでdeadlineの検索
      @tasks = current_user.tasks.where('deadline = ?',deadline)
    else
      @tasks = current_user.tasks
    end

    #タスク内容のキーワードによる絞り込み
    if keyword.present?#ここでkeywordであいまい検索
      @tasks =@tasks.where('content LIKE ? ', "%#{keyword}%")
    end


    #@tasksの並び替えとpage切り分け作業
    @tasks = @tasks.order(deadline: :desc).order(estimated_time: :desc).order(status: :desc).page(params[:page]).per(20)

    #タスク追加フォーム用のtaskのインスタンス化    
    @task = Task.new
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = '登録しました' #一回だけ表示
      redirect_to root_path
    else
      flash.now[:danger] = '登録できませんでした'
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(
      :name, :birthday, :email, :password, :password_confirmation
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        if @current_user
            return @current_user
        else
            @current_user = User.find_by(id: session[:user_id])
            return @current_user
        end
    end

    def logged_in?
        if current_user
            return true
        else
            return false
        end
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/commons/_flash.html.erb
<% flash.each do |type, message|%>
<div class="alert alert-<%= type %>"><%= message%></div>
<% end %>

app/views/commons/_tasks.html.erb
<table class="container roundeddg-light table">
    <tr>
    <th class="text-center"><i class="h4 fas fa-tasks"></i></th><th class="text-center"><i class="h4 fa-solid fa-calendar-days"></i></th><th class="h4 text-center"><i class="fas fa-stopwatch"></i>/分</th><th class="text-center"><i class="h4 fas fa-trash-alt"></i></th>
    </tr>
    <% @tasks.each do |task|%>
    <tr>
        <td>
            <% if task.status == "done" %>
                <div class='task-del-line'>
                <a href="<%= task_path(task, "task[status]" => "todo") %>" data-method="patch"><i class="fas fa-check-square"></i></i></a>
                <span><%= task.content %></span></div>
            <% else %>
                <a href="<%= task_path(task, "task[status]" => "done") %>" data-method="patch"><i class="fas fa-square"></i></a>
                <%= task.content %>
            <% end %>
        </td>

        <!--締め切り日-->
        <% if task.deadline.present?%>
            <td class="text-center"><%= task.deadline.strftime("%m/%d") %></td>
        <% else %>
            <td class="text-center"><%= task.deadline%></td>
        <% end %>

        <td class="text-center"><%= task.estimated_time %></td>

        <td>      
        <a data-confirm="削除しますか？"rel="nofollow" data-method="delete" href="<%= task_path(task) %>"><div class="text-center"><i class="fas fa-trash-alt"></i></div></a>
</td>
    </tr>
    <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>簡単ToDo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/eeb70c0397.js" crossorigin="anonymous"></script>
  </head>

  <body class="bg-light"><!--背景色の変更-->
  <p>
  <% unless logged_in? %>
    <%= link_to '会員登録', signup_path%>
    <%= link_to 'ログイン', signin_path%>
  <% end %>
  </p>
<div class="text-end">
  <% if logged_in? %>
    <a href="/"><i class="h5 fas fa-home"></i></a>
    <a rel="nofollow" data-method="delete" href="/signout"><i class="h5 fas fa-sign-out-alt"></i></a>
  <% end %>
</div>
  <p>
    <%= render 'commons/flash' %>
    <%= yield %>
  </p>
  </body>
</html>

app/views/tasks/_form.html.erb
<dl>
    <dt>タスク内容</dt>
    <dd><%= f.text_field :content %></dd>
</dl>

app/views/tasks/show.html.erb
<h3>タスク詳細</h3>
<dl>
    
    <dt>タスク内容</dt>
    <dd><%= @task.content %></dd>

</dl>

<hr>
<% if @task.user_id == current_user.id%>
<%= link_to '編集ボタン', edit_task_path(@task)%>
|
<%#= link_to "hoge", {controller: "tasks", action: "destroy"}, method: :post %>
<%= link_to '削除ボタン', controller: "tasks", action: "destroy", id: @task , method: :post %>
<%#= link_to '削除ボタン', task_path(@task), method:delete, data: {confirm: '削除しますか？'} %>
<% end %>

app/views/users/new.html.erb
<h3>会員登録</h3>
<%= form_with(model: @user, url: signup_path) do |f|%>
<dl>
    <dt>氏名</dt>
    <dd><%= f.text_field :name %></dd>
    <dt>生年月日</dt>
    <dd><%= f.date_field  :birthday%></dd>
    <dt>E-mail</dt>
    <dd><%= f.email_field :email %></dd>
    <dt>パスワード</dt>
    <dd><%= f.password_field :password %></dd>
    <dt>パスワード（確認）</dt>
    <dd><%= f.password_field :password_confirmation %></dd>
</dl>
<%= f.submit '会員登録'%>
<% end %>

app/views/users/show.html.erb
<div class="d-flex bd-highlight">
    <div class="p-2 w-100 bd-highlight">
      <h3 class="bg-secondary text-center rounded-pill text-white">
      ToDo<br>
      <% if params[:deadline].present? %>
          <i class="h5 text-white fa-solid fa-calendar-days"></i><%=params[:deadline]%>
          <br>
      <% end %>
      <% if params[:keyword].present? %>
          <%= "検索ワード 『#{params[:keyword]}』"%>
      <% end %>
      </h3>

      <%= render 'commons/tasks' %>
    </div>
  <div class="p-4 flex-shrink-1 bd-highlight">

    <!--検索フォーム-->
    <div class="mb-2 p-4 bg-secondary rounded">
    <h6 class="text-white text-center">検索フォーム</h6>
    <%= form_with url: search_path, method: :get, local: true do |f| %>
      <i class="h6 text-white fa-solid fa-calendar-days"></i>  <%= f.date_select :deadline , include_blank: true,use_month_numbers: true, selected: Date.today%><br>
      <br>
      <input type="text" name="keyword" id="keyword" placeholder="検索ワード">
      <br>
          <%= f.button :type => "submit", style: 'background: none; border-style: none;' do %>
          <i class="h6 text-white fas fa-search"></i>
          <% end %>
          <%= link_to '検索解除', root_path, class: "text-white"%>
      <% end %>

    </div>

    <!--ToDO追加フォーム-->
    <div class="mb-2 p-4 bg-secondary rounded">
    <h6 class="mb-2 text-white text-center">ToDo追加フォーム</h6>
      <%= form_with model: @task do |f|%>
          <div><i class="h6 text-white fa-solid fa-calendar-days"></i> <%= f.date_select :deadline, use_month_numbers: true %></div>
          <br>
          <div class="mb-4 text-white"><i class="fas fa-stopwatch"></i>/分
          <%= f.select :estimated_time, {"15分"=> "15","30分"=> "30","45分"=> "45", "60分"=> "60", "90分"=> "90","120分"=> "120","180分"=> "180"},include_blank: true%>
          <br></div>
          <input type="text" name="task[content]" id="task_content" placeholder="タスク内容">
          <%= f.button :type => "submit", style: 'background: none; border-style: none;' do %>
          <i class="text-white fa-2x fas fa-plus-circle"></i>
          <% end %>

      <% end %>
    </div>

  </div>
</div>

<%#ページネーション用の記述%>
<h3 class="text-center"><%= paginate @tasks %></h3>